apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  selector:
    matchLabels:
      app: go-web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
      - name: go-web-app
        image: teopasc/go-web-app:latest # Replace with the image name
        ports:
        - containerPort: 8080
