name: Build and Push Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 
            - go-web-app:latest 
            - go-web-app:${{ github.sha }} 
          file: ./Dockerfile
